# ----------------------------------------------------------------
# CircleCIの最新の2.1バージョンのパイプラインプロセスエンジンを使用すること
# ----------------------------------------------------------------

# CircleCIの設定ファイルのバージョンを指定。2.1は、CircleCIの最新の構成機能を使用する
version: 2.1
# CircleCIの「オーブ」と呼ばれる再利用可能な構成要素を定義。特定の機能（AWS CLI、CloudFormation、Ansible、Ruby）を使用できる
orbs:
  # AWS CLIオーブのバージョン4.1.3をインポート。AWS CLIコマンドを使用する
  aws-cli: circleci/aws-cli@4.1.3
  # CloudFormationオーブのバージョン0.1.6をインポート。CloudFormationスタックの操作を支援
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  # Ansibleプレイブックオーブのバージョン0.0.5をインポート。Ansibleを使ったデプロイを簡素化
  ansible-playbook: orbss/ansible-playbook@0.0.5
  # Rubyオーブのバージョン2.1.3をインポート。Ruby環境を簡単に設定
  ruby: circleci/ruby@2.1.3
  # Pythonオーブをインポートする
  python: circleci/python@2.0.3

# ----------------------------------------------------------------
# ワークフロー内で後ほど呼び出される「ジョブ」を定義する
# jobs セクションはCircleCIの設定ファイル内で「実行するタスクの単位」を定義
# ----------------------------------------------------------------

# jobs セクションの開始
jobs:
  # ジョブの名前。execute-cloudformationという名前で、CloudFormationスタックをデプロイするタスクを定義
  execute-cloudformation:
    # CircleCIの aws-cloudformation オーブが提供するデフォルトの環境
    executor: aws-cloudformation/default
    # このジョブで実行されるアクション（ステップ）のリスト
    steps:
      # リポジトリからソースコードをチェックアウトして、ジョブが必要とするファイルを取得するステップ
      - checkout
      # AWS CLI（コマンドラインインターフェース）をセットアップするステップ
      # aws_access_key_id, aws_secret_access_keyは、環境変数から読み取られるAWS認証情報
      # regionは、AWSの操作を行うリージョンを指定
      # オーブが提供する特定のコマンドやジョブの使い方が既に定義されている
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      # AWS CloudFormationのテンプレートを使用してスタックをデプロイ
      # オーブが提供する特定のコマンドやジョブの使い方が既に定義されている
      - aws-cloudformation/deploy:
          # デプロイされるCloudFormationスタックの名前
          stack-name: stack-lecture13
          # CloudFormationテンプレートファイルのパス
          template-file-path: cloudformation/stack-lecture13.yml
          # IAMロールの作成・更新に必要な権限を指定
          capabilities: CAPABILITY_NAMED_IAM
          #  テンプレートのパラメータを指定。RDSpasswordに環境変数AWS_DB_PWの値を設定($AWS_DB_PWは事前に手動設定しておきCircleCIの環境変数に登録)
          parameter-overrides: RDSpassword=$AWS_DB_PW

      # 任意のコマンドを実行するステップを指定。これから実行する内容を定義
      - run:
          # ステップの名前。set environment variableという名前。名前は自由に設定でき、何をしているステップかを説明するためのもの
          name: set environment variable
          # 実際に実行するコマンドを指定。| は次の行に続けてコマンドを書けることを示すもので、複数行のスクリプトを記述するために使用
          # set -x :シェルで実行されるすべてのコマンドを表示するデバッグモードを有効にする。後でコマンドがどのように実行されたかをデバッグしやすくなる
          # echo exportについてはCloudformationテンプレートのOutputセクションから値を取得する。
          # 上記値を環境変数として設定するためのコマンド
          #EC2のパブリックIPアドレスを取得し、AWS_EC2_IP環境変数に設定
          # RDSのエンドポイントを取得し、AWS_DB_ENDPOINT環境変数に設定
          # ALBのホスト名を取得し、AWS_ALB_HOST環境変数に設定
          # S3バケット名を取得し、AWS_S3_BUCKET環境変数に設定
          # $BASH_ENVという特別な環境変数を使用することで、スクリプト内で設定した環境変数を後続のジョブやステップで利用可能にすることができる
          command: | 
            set -x
            #EC2publicIP
            echo export AWS_EC2_IP="$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='EC2PublicIpAddress'].OutputValue" --output text)" >> $BASH_ENV
            #DB_Endpoint
            echo export AWS_DB_ENDPOINT="$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='RDSEndpoint'].OutputValue" --output text)" >> $BASH_ENV
            #ALB_host
            echo export AWS_ALB_HOST="$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='ALBDNSName'].OutputValue" --output text)" >> $BASH_ENV
            #S3bucket
            echo export AWS_S3_BUCKET="$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='S3BuckeName'].OutputValue" --output text)" >> $BASH_ENV
      - run:
          # $BASH_ENVファイルの内容を表示。環境変数が正しく設定されたかどうかを確認
          name: cat $BASH_ENV
          command: |
              cat $BASH_ENV
      # $BASH_ENVファイルの内容をenv_var.shという名前のファイルにコピー。環境変数が記載されたファイルを作成
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello