---
# yarnがインストールされているかを確認し、もしインストールされていなければ指定されたバージョンのyarnをインストール
# 次に、依存パッケージをインストールするためにyarn installを実行
- name: Check if yarn is installed
  ansible.builtin.command:
    cmd: yarn -v
  register: yarn_check
  ignore_errors: true
  changed_when: false

- name: Install yarn
  ansible.builtin.shell:
    cmd: /bin/bash -lc "npm install -g yarn@{{yarn_version}}"
  register: yarn_install
  when: yarn_check.failed

- name: Install dependencies packages
  ansible.builtin.shell:
    cmd: /bin/bash -lc "yarn install"
  register: result_cmd
  args:
    chdir: "{{app_dir}}"
  when: yarn_check.failed
