---
# MySQLがインストールされているか確認する内容
- name: Check if mysql is installed
  ansible.builtin.command:
    cmd: which mysql && mysql --version
  register: mysql_check
  ignore_errors: true
  changed_when: false

# MySQL のインストールを行うタスク
- name: Install mysql
  ansible.builtin.yum:
    name: mysql
    state: present
  become: yes
  when: mysql_check is defined and mysql_check.failed

# MySQL 開発用パッケージ mysql-devel をインストールするタスク
- name: Install mysql-devel
  ansible.builtin.yum:
    name: mysql-devel
    state: present
  become: yes
  when: mysql_check is defined and mysql_check.failed

# MySQL公式リポジトリを追加する（必要に応じて）
- name: Add MySQL official repository
  ansible.builtin.yum_repository:
    name: mysql
    description: MySQL Repository
    baseurl: https://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/
    gpgcheck: yes
    gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql
  become: yes