---
# bundler が指定したバージョンでインストールされているか確認
- name: Check if bundler is installed
  # コマンドモジュールを使って直接シェルコマンドを実行
  ansible.builtin.command:
    # 指定されたバージョンの bundler がインストールされているか確認するコマンド
    cmd: bundler _{{bundler_version}}_ --version
  # コマンドの実行ディレクトリを app_dir に設定。ここにアプリをインストールする
  args:
    # このディレクトリが存在しないのでは？★
    chdir: "{{app_dir}}"
  register: bundler_check
  # コマンドが失敗してもエラーを無視して次のタスクに進む
  ignore_errors: true
  # インストール確認だけでタスクでシステムの状態は変更されないので、falseに設定
  changed_when: false

# Bundlerのインストール
- name: Install bundler
  # shell モジュールを使用して指定のシェルコマンドを実行
  ansible.builtin.shell:
    # 定されたバージョンのBundlerをインストール
    cmd: /bin/bash -lc "gem install bundler -v {{bundler_version}}"
  # 実行結果を bundler_install
  register: bundler_install
  # bundler_check.failed の場合（つまり、Bundlerが指定バージョンで存在しない場合）のみこのタスクが実行
  when: bundler_check.failed