- name: yum update all packages
  become: true
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install pip
  become: true
  yum:
    name: python-pip
    state: present

- name: uninstall MariaDB
  become: true
  yum:
    name: mariadb*
    state: absent

- name: Install PyMySQL
  become: true
  pip:
    name: PyMySQL
    state: present

- name: Install RPM-GPG-KEY-mysql
  become: true
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  ignore_errors: true

- name: install mysql repository
  become: true
  yum:
    name: "https://repo.mysql.com/mysql80-community-release-el7-1.noarch.rpm"
    state: present

- name: install mysql packages
  become: true
  yum:
    name:
      - mysql-community-devel
      - mysql-community-server
      - mysql-community-client
    state: present

- name: Start MySQL service
  become: true
  systemd:
    name: mysqld
    state: started
  ignore_errors: false

- name: use mysql_native_password
  community.mysql.mysql_user:
    name: admin
    host: "%"
    password: "{{ MasterUserPassword }}"
    login_user: admin
    login_password: "{{ MasterUserPassword }}"
    login_host: "{{ EndpointAddress }}"
    priv: "*.*:ALL,GRANT"
    state: present
    plugin: mysql_native_password
  ignore_errors: true