---
- name: Configure MySQL repository and install packages
  hosts: all
  become: true
  tasks:

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add MySQL 8.0 repository
      yum:
        name: "https://repo.mysql.com/mysql80-community-release-el7-1.noarch.rpm"
        state: present

    - name: Enable MySQL 8.0 repository
      ini_file:
        path: /etc/yum.repos.d/mysql-community.repo
        section: mysql80-community
        option: enabled
        value: "1"

    - name: Disable MySQL 5.7 repository (if present)
      ini_file:
        path: /etc/yum.repos.d/mysql-community.repo
        section: mysql57-community
        option: enabled
        value: "0"

    - name: Install MySQL packages
      yum:
        name:
          - mysql-community-server
          - mysql-community-client
          - mysql-community-devel
        state: present

    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        state: started
        enabled: true
